name: hello_world
description: A basic Hello World Flutter app.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.13.4

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
